### ISSUE TITLE
Computing the smallest eigenpairs

### ISSUE THREAD

**Issue by themightyoarfish** [noahgolmant/pytorch-hessian-eigenthings#11]
Is it possible to use this method as well to compute the smallest eigenpairs as well?
I would like to see whether this is useful in the context of [this work](https://openreview.net/pdf?id=S1iiddyDG): Negative Eigenvalues of the Hessian in Deep Neural Networks.

**Comment by themightyoarfish** [comment]
[This SE](https://math.stackexchange.com/a/271876) answer (and the comments) seem to suggest that performing the same power iteration on B = A − λ_max * I (i.e. subtracting the largest EV from the diagonal) would yield the smallest (most negative) EV (the question is about smallest magnitude, but one comment states that). 

Can you confirm this? Is it possible without computing the largest one first?

**Comment by noahgolmant** [comment]
Implementation-wise (if you are up to it), this amounts to:
(1) Computing the largest principal eigenvalue, call it `p`.
(2) Creating a `LambdaOperator` that just does computes `HVPOperator.apply(x) - p * x`. Run the deflated power iteration routine with this new operator. Add `p` to all the eigenvalues at the end.

**Comment by themightyoarfish** [comment]
So basically, use the existing code to obtain `p`, subclass the `HVPOperator` and overrid `apply()` with `return super().apply() - p * vec`? That would seem simple enough.

**Comment by noahgolmant** [comment]
There's no need to subclass `HVPOperator`. You can create a `LambdaOperator` where the provided lambda function is `lambda x: hvp_op.apply(x) - p * x`.
