### ISSUE TITLE
which epoch or iteration time point to compute tok-n eigenvalue ,eigenvector?

### ISSUE THREAD

**Issue by Tron-x** [noahgolmant/pytorch-hessian-eigenthings#20]
when i run this code .it will return top-n eigenvalue and eigenvector, but i can't find which training epoch or iteration checkpoint the eigenvalue and eigenvector is , because when training(every iteration) the hessian matrix is changing ,so the eigenvalue and eigenvector is also changing . so the returned result is at which training time point ?

**Comment by noahgolmant** [comment]
I use `track` to log data generally. The example code just loads a randomly initialized model. You can use this module to compute the spectrum for your model throughout training -- you just have to call the function every epoch. In your training loop, once you update your `model` through some step of SGD, you can call the `compute_hessian_eigenthings` on that model to get the eigenvalues for that iteration/epoch. You can store them however you want (I use `track`).
