### ISSUE TITLE
AttributeError: 'HVPOperator' object has no attribute 'zero_grad'

### ISSUE THREAD

**Issue by neerajkuhike** [noahgolmant/pytorch-hessian-eigenthings#38]
I am facing this issue when running resnet 18 on cifar 10 dataset.

**Comment by AjinkyaBankar** [comment]
Did you get the solution? I am also facing the same problem.

**Comment by noahgolmant** [comment]
This should be fixed now in master! The error was because I renamed `zero_grad` to `_zero_grad` in a previous PR!
